/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import datos.*;
import entidades.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import logica.*;
/**
 *
 * @author sistemas
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnListarEstudiantes = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        mnuiRegistroAsignaturas = new javax.swing.JMenu();
        mnuiAgregarEstudiante = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuListados = new javax.swing.JMenu();
        mnuiListarEstudiantes = new javax.swing.JMenuItem();
        mnuiListaDatosE = new javax.swing.JMenuItem();
        mnuiListaDatosA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de estudiantes");

        btnAgregar.setBackground(new java.awt.Color(0, 255, 153));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_file.gif"))); // NOI18N
        btnAgregar.setText("Agregar estudiante");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnListarEstudiantes.setBackground(new java.awt.Color(102, 255, 0));
        btnListarEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListarEstudiantes.setText("Listar estudiantes");
        btnListarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEstudiantesActionPerformed(evt);
            }
        });

        menuPrincipal.setForeground(new java.awt.Color(0, 20, 2));

        mnuiRegistroAsignaturas.setMnemonic('P');
        mnuiRegistroAsignaturas.setText("Registrar");
        mnuiRegistroAsignaturas.setToolTipText("");
        mnuiRegistroAsignaturas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuiAgregarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuiAgregarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_file.gif"))); // NOI18N
        mnuiAgregarEstudiante.setText("Registrar estudiante");
        mnuiAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAgregarEstudianteActionPerformed(evt);
            }
        });
        mnuiRegistroAsignaturas.add(mnuiAgregarEstudiante);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_file.gif"))); // NOI18N
        jMenuItem1.setText("Registrar asignaturas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuiRegistroAsignaturas.add(jMenuItem1);

        menuPrincipal.add(mnuiRegistroAsignaturas);

        mnuListados.setMnemonic('L');
        mnuListados.setText("Listados");
        mnuListados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuiListarEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuiListarEstudiantes.setText("Listar estudiantes");
        mnuiListarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListarEstudiantesActionPerformed(evt);
            }
        });
        mnuListados.add(mnuiListarEstudiantes);

        mnuiListaDatosE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuiListaDatosE.setText("Lista de datos estudiante");
        mnuiListaDatosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListaDatosEActionPerformed(evt);
            }
        });
        mnuListados.add(mnuiListaDatosE);

        mnuiListaDatosA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuiListaDatosA.setText("Lista de datos asignatura");
        mnuiListaDatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListaDatosAActionPerformed(evt);
            }
        });
        mnuListados.add(mnuiListaDatosA);

        menuPrincipal.add(mnuListados);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnListarEstudiantes)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarEstudiantes)
                    .addComponent(btnAgregar))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAgregarEstudianteActionPerformed
        FrmRegistrarEstudiantes frmRegistrarEstudiantes = new FrmRegistrarEstudiantes(this, blEstudiantes);
        frmRegistrarEstudiantes.setVisible(true);
    }//GEN-LAST:event_mnuiAgregarEstudianteActionPerformed

    private void btnListarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEstudiantesActionPerformed
        FrmListadoEstudiantes frmListadoEstudiantes = new FrmListadoEstudiantes(this);
        frmListadoEstudiantes.setVisible(true);
    }//GEN-LAST:event_btnListarEstudiantesActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        FrmRegistrarEstudiantes frmRegistrarEstudiantes = new FrmRegistrarEstudiantes(this, blEstudiantes);
        frmRegistrarEstudiantes.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void mnuiListarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListarEstudiantesActionPerformed
        FrmListadoEstudiantes frmListadoEstudiantes = new FrmListadoEstudiantes(this);
        frmListadoEstudiantes.setVisible(true);
    }//GEN-LAST:event_mnuiListarEstudiantesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String input = JOptionPane.showInputDialog(
        null, 
        "Ingresar código de estudiante:",
        "Verificacion de datos",
        JOptionPane.QUESTION_MESSAGE);
try {
    int codigo = Integer.parseInt(input);
    boolean idExiste = false;
    String apellidoYNombreEstudiante = null;

    for (int i = 0; i < DALEstudiantes.getNumeroRegistros(); i++) {
        Estudiante estudiante = DALEstudiantes.getEstudiante(i);
        if (estudiante.getCodigo() == codigo) {
            idExiste = true;
            apellidoYNombreEstudiante = estudiante.getApellido()+" "+
                    estudiante.getNombre(); // Obtener el nombre del estudiante encontrado
            break;
        }
    }

    if (idExiste) {
        JOptionPane.showMessageDialog(null, 
                "Verificación exitosa",
                "Verificación de datos",
                JOptionPane.INFORMATION_MESSAGE);
        
        
        FrmRegistroAsignaturas frmRegistroAsignaturas = new FrmRegistroAsignaturas(this);
        frmRegistroAsignaturas.setDato(apellidoYNombreEstudiante);
        frmRegistroAsignaturas.setVisible(true);
        
        
        
    } else {
        JOptionPane.showMessageDialog(null, 
                "El código ingresado no existe.",
                "Verificación de datos",
                JOptionPane.ERROR_MESSAGE);
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, 
                "Error: Ingresa un valor válido para el código (números).",
                "Verificación de datos",
                JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuiListaDatosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListaDatosEActionPerformed
        String input = JOptionPane.showInputDialog(
        null, 
        "Ingresar código:",
        "Verificacion de datos",
        JOptionPane.QUESTION_MESSAGE);
try {
    int codigo = Integer.parseInt(input);
    boolean idExiste = false;
    String apellidoYNombreEstudiante = null;

    for (int i = 0; i < DALEstudiantes.getNumeroRegistros(); i++) {
        Estudiante estudiante = DALEstudiantes.getEstudiante(i);
        if (estudiante.getCodigo() == codigo) {
            idExiste = true;
            apellidoYNombreEstudiante = estudiante.getApellido()+" "
                    + estudiante.getNombre();// Obtener el nombre del estudiante encontrado
            break;
        }
    }

    if (idExiste) {
        JOptionPane.showMessageDialog(null, 
                "Verificación exitosa",
                "Verificación de datos",
                JOptionPane.INFORMATION_MESSAGE);
        FrmListadoDatosEstudiante frmListadoDatosEstudiante = new FrmListadoDatosEstudiante(this);
        frmListadoDatosEstudiante.setDato(apellidoYNombreEstudiante);
        frmListadoDatosEstudiante.codigoIngresado(codigo);
        frmListadoDatosEstudiante.setVisible(true);
        } else {
        JOptionPane.showMessageDialog(null, 
                "El código ingresado no existe.",
                "Verificación de datos",
                JOptionPane.ERROR_MESSAGE);
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, 
                "Error: Ingresa un valor válido para el código (números).",
                "Verificación de datos",
                JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_mnuiListaDatosEActionPerformed

    private void mnuiListaDatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListaDatosAActionPerformed
        
    }//GEN-LAST:event_mnuiListaDatosAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnListarEstudiantes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu mnuListados;
    private javax.swing.JMenuItem mnuiAgregarEstudiante;
    private javax.swing.JMenuItem mnuiListaDatosA;
    private javax.swing.JMenuItem mnuiListaDatosE;
    private javax.swing.JMenuItem mnuiListarEstudiantes;
    private javax.swing.JMenu mnuiRegistroAsignaturas;
    // End of variables declaration//GEN-END:variables

    private BLEstudiantes blEstudiantes;
}

